language: nodejs
node_js:  
- 11.6.0
cache: npm
install:
  - npm ci
  - yarn install
  

script:
  - yarn test
  - yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on: 
    branch: master




